### PR TITLE
update to version 3.0.3.778

### PR DESCRIPTION
**Pull request by tommueller**
fix for https://github.com/ciricihq/gitlab-sonar-scanner/issues/6

### CODE REVIEW

**Comment by gtrias** [comment]
thanks for the PR @tommueller 
@elboletaire could we do docker image tags in order to test this new version?

**Comment by elboletaire** [comment]
Yeah we should indeed @gtrias, but there's that strange issue about versioning tags in docker hub... I don't know if we could do it that way, or we'll need to do it using travis (or any other CI).

**Comment by gtrias** [comment]
I've created a branch `test` to make a docker image with the same name.

We'll test with some projects and will be merged after be checked.

**Review by gtrias — APPROVED** [review]

**Review by elboletaire — APPROVED** [review]

**Comment by tommueller** [comment]
:+1:

**Comment by gtrias** [comment]
fix #6

**Pull request merged**
