### PR TITLE
Update sonar scanner to 3.2.0.1227

### PR DESCRIPTION
**Pull request by bartleboeuf**
I update URL and release version of the sonar scanner, and some cleaning

### CODE REVIEW

**Comment by gtrias** [comment]
Thank you @bartleboeuf !

I'll try to implement some basic testing using travis (see #4 ) in order to test this new version.
Later we'll publish this new version

cc @elboletaire

**Comment by elboletaire** [comment]
@bartleboeuf can you please explain why have you added the TZ in there? Take in mind that the build process runs on our own, so does not make much sense to have it there. You better define the timezone volume for your runner on its configuration (gitlab-runner `config.toml` file):

~~~toml
[runners.docker]
  volumes = ["/usr/share/zoneinfo/Europe/Paris:/etc/localtime"]
~~~

If you're doing this cos' you wanna be able to change it on the fly, we should modify the entrypoint to be able to handle it; afaik setting `TZ` does nothing with docker run (some images automatically switch the timezone with the `TZ` var, but not the one we used apparently), and we should do that linking process directly on the entrypoint file.

**Comment by bartleboeuf** [comment]
@elboletaire I added the TZ to have the correct time in the log timestamps. We don't want to change it at runtime. But, I still agree that this can be done in sonar-scanner-run.sh

**Comment by elboletaire** [comment]
Yeah but doing it that way you're setting the correct time **for you**. We'll need to manage this in the entrypoint file, so this code should be removed here (as has nothing to do with updating the client itself, are two different issues btw).

**Comment by hansingt** [comment]
As this PR seems to be dead I took it over at https://github.com/ciricihq/gitlab-sonar-scanner/pull/34

**Comment by elboletaire** [comment]
Closed in favor of #35

**Pull request closed without merging**
